<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Title>LangSharp</Title>
		<Authors>AnthonnyDev</Authors>
		<Description>LangSharp SDK is a .NET 8 library that leverages Python.NET to communicate with AI providers, utilizing powerful Python resources such as LangChain. This SDK provides a robust framework for executing Python commands and scripts within a .NET environment, enabling seamless integration with various AI services.</Description>
		<Copyright>Copyright © 2025 $(Authors)</Copyright>
		<PackageProjectUrl>https://github.com/AnthonnyLac/LangSharp</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/AnthonnyLac/LangSharp</RepositoryUrl>
		<PackageTags>python;dotnet;sdk;integration</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<Version>1.0.20</Version>
	</PropertyGroup>

	<ItemGroup>
		<None Update="Scripts\**\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.4" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.4" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.4" />
		<PackageReference Include="NuGet.Configuration" Version="6.13.2" />
		<PackageReference Include="python" Version="3.11.7" />
		<PackageReference Include="pythonnet" Version="3.0.5" />
	</ItemGroup>

	<ItemGroup>
		<None Include="../../README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>


</Project>
