name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      configuration: Release

  test:
    uses: ./.github/workflows/tests.yml
    needs: build 
    with:
      configuration: Release

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Restore dependencies
      run: dotnet restore 

    - name: Build project
      run: dotnet build ./src/LangSharp/LangSharp.csproj -c Release

    - name: Pack project
      run: dotnet pack ./src/LangSharp/LangSharp.csproj -c Release -o out
      
    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./out/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
