name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      configuration: Release

  test:
    uses: ./.github/workflows/tests.yml
    needs: build 
    with:
      configuration: Release

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push src/LangSharp/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
