name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
      - develop
      - types: [opened, synchronize, reopened]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      configuration: Release

  test:
    uses: ./.github/workflows/tests.yml
    needs: build 
    with:
      configuration: Release

  sonar:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/sonar.yml
    needs: test
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    with:
      configuration: Release