# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches: 
      - main
      - develop
  pull_request:
    branches: 
      - main
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
    
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"

    - name: Extract coverage value
      run: |
        COVERAGE_FILE=$(find TestResults -name "coverage.cobertura.xml" | head -n 1)
        COVERAGE_VALUE=$(grep -oP '(?<=line-rate=")[0-9.]+(?=")' "$COVERAGE_FILE")
        echo "Code Coverage: $COVERAGE_VALUE" >> $GITHUB_STEP_SUMMARY
