name: Test Workflow

on:
  workflow_call: 
    inputs:
      configuration:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore 

    - name: Build test project
      run: dotnet build tests/LangSharp.UnitTests/LangSharp.UnitTests.csproj

    - name: Run tests
      run: dotnet test --no-build --verbosity detailed